name: Deploy to Production - QI
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: GitHub Action Deploy to WP Engine
              uses: wpengine/github-action-wpe-site-deploy@v3
              with:
                  WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
                  WPE_ENV: quincyinst
                  SRC_PATH: './'
                  REMOTE_PATH: 'wp-content/themes/bop/'
                  FLAGS: -azvr --inplace --delete --exclude=".*"
                  CACHE_CLEAR: TRUE
